# This is a basic workflow to help you get started with Actions

name: Builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        
      - name: Deploy webpage ğŸ•¸ï¸
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages-build
          folder: public
          target-folder: docs

      - name: Install and Build project (non-production) ğŸ”§
        run: |
          npm install
          npm run build

      - name: Deploy project (non-production) ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages-build # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          target-folder: docs/scripts
      
      - name: Remove non-production files
        uses: JesseTG/rm@v1.0.2
        with:
          path: dist
      
      - name: Install and Build project (production) ğŸ”§
        run: |
          npm install
          npm run build:prod

      - name: Deploy project (production) ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages-build # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          target-folder: docs/scripts/prod

  build-docs:
    runs-on: ubuntu-latest
    needs: [build-library]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        
      - name: Install and Build docsğŸ”§
        run: |
          npm install
          npm run docs:gen
          
      - name: Deploy docsğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages-build
          folder: docs
          target-folder: docs/docs

  release-to-npm:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [build-docs]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build project ğŸ”§
        run: npm install

      - name: Releasing on npm ğŸ’»
        run: npm run semantic-release
        env: 
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


