# This is a basic workflow to help you get started with Actions

name: Builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build project ğŸ”§
        run: |
          npm install
          npm run build

      - name: Deploy project ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages-build # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          target-folder: docs/scripts
          
      - name: Install and Build docsğŸ”§
        run: |
          npm install
          npm run docs:gen
      - name: Deploy docsğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages-build
          folder: docs
          target-folder: docs/docs
